/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Capability,  ChangeRequestPlan,  Dependency,  DependencyType,  Epic,  Feature,  FeatureModification,  FlowAction,  FlowActionTriggerType,  FlowScreen,  FlowToCapabilityMapping,  ImpactAnalysis,  LayeredProject,  NarrativeLayer,  ProductIntent,  RiskLevel,  SpecificationLayer,  StructureLayer,  SubIntent,  Task,  TaskModification,  TaskType,  TaskUpdate,  TechnicalRequirement,  TechnicalRequirementType,  UXSpec,  UserStory } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface Capability {
      name?: string | null
      description?: string | null
      linkedUserStoryNames: string[]
    }
    export interface ChangeRequestPlan {
      description?: string | null
      new_features: Feature[]
      modified_features: FeatureModification[]
      new_tasks: Task[]
      modified_tasks: TaskModification[]
      impact_analysis?: ImpactAnalysis | null
    }
    export interface Dependency {
      from_description?: string | null
      to_description?: string | null
      type?: types.DependencyType | null
    }
    export interface Epic {
      name?: string | null
      description?: string | null
      userStoryNames: string[]
    }
    export interface Feature {
      name?: string | null
      description?: string | null
      linked_intent?: string | null
      tasks: Task[]
      ux_spec?: UXSpec | null
    }
    export interface FeatureModification {
      feature_name?: string | null
      reason?: string | null
      new_tasks: Task[]
      updated_tasks: TaskUpdate[]
    }
    export interface FlowAction {
      name?: string | null
      description?: string | null
      triggerType?: types.FlowActionTriggerType | null
      parentScreenName?: string | null
      nextScreenName?: string | null
      linkedCapabilityNames: string[]
    }
    export interface FlowScreen {
      name?: string | null
      description?: string | null
      actionNames: string[]
    }
    export interface FlowToCapabilityMapping {
      flowActionName?: string | null
      capabilityNames: string[]
      rationale?: string | null
    }
    export interface ImpactAnalysis {
      affected_features: string[]
      affected_tasks: string[]
      reasoning?: string | null
      risk_level?: types.RiskLevel | null
    }
    export interface LayeredProject {
      narrativeLayer?: NarrativeLayer | null
      structureLayer?: StructureLayer | null
      specificationLayer?: SpecificationLayer | null
    }
    export interface NarrativeLayer {
      epics: Epic[]
      userStories: UserStory[]
    }
    export interface ProductIntent {
      name?: string | null
      description?: string | null
      sub_intents: SubIntent[]
    }
    export interface SpecificationLayer {
      technicalRequirements: TechnicalRequirement[]
      tasks: Task[]
    }
    export interface StructureLayer {
      capabilities: Capability[]
      flowScreens: FlowScreen[]
      flowActions: FlowAction[]
      mappings: FlowToCapabilityMapping[]
    }
    export interface SubIntent {
      name?: string | null
      description?: string | null
      features: Feature[]
    }
    export interface Task {
      type?: types.TaskType | null
      description?: string | null
      dependencies: string[]
    }
    export interface TaskModification {
      task_description?: string | null
      modification_reason?: string | null
      new_description?: string | null
    }
    export interface TaskUpdate {
      original_description?: string | null
      new_description?: string | null
      reason?: string | null
    }
    export interface TechnicalRequirement {
      type?: types.TechnicalRequirementType | null
      specification?: string | null
      linkedCapabilityNames: string[]
    }
    export interface UXSpec {
      experience_goal?: string | null
      design_refs: string[]
    }
    export interface UserStory {
      narrative?: string | null
      acceptanceCriteria: string[]
      epicName?: string | null
      linkedCapabilityNames: string[]
    }
}