/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum DependencyType {
  Requires = "Requires",
  Blocks = "Blocks",
  Impacts = "Impacts",
  Supersedes = "Supersedes",
}

export enum FlowActionTriggerType {
  User = "User",
  System = "System",
}

export enum RiskLevel {
  Low = "Low",
  Medium = "Medium",
  High = "High",
}

export enum TaskType {
  Backend = "Backend",
  Frontend = "Frontend",
  Test = "Test",
  Infrastructure = "Infrastructure",
}

export enum TechnicalRequirementType {
  Performance = "Performance",
  Security = "Security",
  Scalability = "Scalability",
  Reliability = "Reliability",
  Other = "Other",
}

export interface Capability {
  name: string
  description: string
  linkedUserStoryNames: string[]
  
}

export interface ChangeRequestPlan {
  description: string
  new_features: Feature[]
  modified_features: FeatureModification[]
  new_tasks: Task[]
  modified_tasks: TaskModification[]
  impact_analysis: ImpactAnalysis
  
}

export interface Dependency {
  from_description: string
  to_description: string
  type: DependencyType
  
}

export interface Epic {
  name: string
  description: string
  userStoryNames: string[]
  
}

export interface Feature {
  name: string
  description: string
  linked_intent: string
  tasks: Task[]
  ux_spec?: UXSpec | null
  
}

export interface FeatureModification {
  feature_name: string
  reason: string
  new_tasks: Task[]
  updated_tasks: TaskUpdate[]
  
}

export interface FlowAction {
  name: string
  description: string
  triggerType: FlowActionTriggerType
  parentScreenName: string
  nextScreenName?: string | null
  linkedCapabilityNames: string[]
  
}

export interface FlowScreen {
  name: string
  description: string
  actionNames: string[]
  
}

export interface FlowToCapabilityMapping {
  flowActionName: string
  capabilityNames: string[]
  rationale: string
  
}

export interface ImpactAnalysis {
  affected_features: string[]
  affected_tasks: string[]
  reasoning: string
  risk_level: RiskLevel
  
}

export interface LayeredProject {
  narrativeLayer: NarrativeLayer
  structureLayer: StructureLayer
  specificationLayer: SpecificationLayer
  
}

export interface NarrativeLayer {
  epics: Epic[]
  userStories: UserStory[]
  
}

export interface ProductIntent {
  name: string
  description: string
  sub_intents: SubIntent[]
  
}

export interface SpecificationLayer {
  technicalRequirements: TechnicalRequirement[]
  tasks: Task[]
  
}

export interface StructureLayer {
  capabilities: Capability[]
  flowScreens: FlowScreen[]
  flowActions: FlowAction[]
  mappings: FlowToCapabilityMapping[]
  
}

export interface SubIntent {
  name: string
  description: string
  features: Feature[]
  
}

export interface Task {
  type: TaskType
  description: string
  dependencies: string[]
  
}

export interface TaskModification {
  task_description: string
  modification_reason: string
  new_description?: string | null
  
}

export interface TaskUpdate {
  original_description: string
  new_description: string
  reason: string
  
}

export interface TechnicalRequirement {
  type: TechnicalRequirementType
  specification: string
  linkedCapabilityNames: string[]
  
}

export interface UXSpec {
  experience_goal: string
  design_refs: string[]
  
}

export interface UserStory {
  narrative: string
  acceptanceCriteria: string[]
  epicName: string
  linkedCapabilityNames: string[]
  
}
